server:
  port: 8081

spring:
  application:
    name: "underwriter-microservice"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: "root"
    password: "password"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/aline_financial"
    initialization-mode: always # This is to automatically insert data.sql

app:
  email:
    enable: true
    from: "no-reply@alinefinancial.com"
  aws:
    email:
      template-bucket-name: "aline-email-templates"
    credentials:
      access-key-id: "${APP_USER_ACCESS_KEY}"
      secret-access-key: "${APP_USER_SECRET_KEY}"
  landing-portal: "${PORTAL_LANDING}"
  member-dashboard: "${PORTAL_DASHBOARD}"
  security:
    secret-key: "xBnkRrjIeZvtl3864JbRjg5rpLhZPneH"
    jwt:
      secret-key: "7y5Phi01FZzd60UJMkGinerMiBgNy4DP"

logging:
  file:
    path: "../home/Documents/logs"
    name: "app.log"


management.endpoints.web.exposure.include: '*'